---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: harbor-jobservice
    namespace: kube-mlops
  hostPath:
    path: /var/lib/libvirt/iscas/harbor/jobservice
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice
  namespace: kube-mlops
  labels:
    name: "harbor-jobservice"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: harbor-registry
    namespace: kube-mlops
  hostPath:
    path: /var/lib/libvirt/iscas/harbor/registry
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: kube-mlops
  labels:
    name: "harbor-registry"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-trivy
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-harbor-trivy-0
    namespace: kube-mlops
  hostPath:
    path: /var/lib/libvirt/iscas/harbor/trivy
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-trivy-0
  namespace: kube-mlops
  labels:
    name: "harbor-trivy"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"
